language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install pylint httpx respx PyYAML pytest hypercorn starlette fastapi respx anyio trio
  - pip install -e .
script:
  - pytest
  - pylint openapi
